export {default as BibliotecaMex} from "../../images/SitiosInteres/bibliotecaMex.jpg";
export {default as BibliotecaVirtualSalud} from "../../images/SitiosInteres/bibliotecavirtualsalud.png";
export {default as Caltech} from "../../images/SitiosInteres/caltech.jpg";
export {default as Cepal} from "../../images/SitiosInteres/cepal.jpg";
export {default as Ciidet} from "../../images/SitiosInteres/ciidet.jpg";
export {default as Cochrane} from "../../images/SitiosInteres/cochrane.jpg";
export {default as CulturaUnam} from "../../images/SitiosInteres/culturaUnam.jpg";
export {default as Doaj} from "../../images/SitiosInteres/doaj.jpg";
export {default as Hemeroteca} from "../../images/SitiosInteres/hemeroteca.jpg";
export {default as Etd} from "../../images/SitiosInteres/etd.jpg";
export {default as FreeMedical} from "../../images/SitiosInteres/freeMedical.jpg";
export {default as Imslp} from "../../images/SitiosInteres/imslp.jpg";
export {default as InvestigacionEconomica} from "../../images/SitiosInteres/investigacionEconomicas.jpg";
export {default as PubMed} from "../../images/SitiosInteres/pubmed.jpg";
export {default as Rebiun} from "../../images/SitiosInteres/rebiun.jpg";
export {default as RevistaDigital} from "../../images/SitiosInteres/revistaDigital.jpg";
export {default as Unadm} from "../../images/SitiosInteres/unadm.jpg";
export {default as Wdi} from "../../images/SitiosInteres/wdi.jpg";

